---
title: "Data Analysis on Boston Weather"
author: "Seeam S. Noor"
date: "February 12, 2019"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, echo = FALSE, error = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

  library(tidyverse)
  # Loading the data we need

  boston_weather = read_csv("boston_weather.csv")
  
  # install.packages("lubridate")
  
  library(lubridate)
  
  # install.packages('ggridges')
  
  library(ggridges)
  
  # install.packages("viridis")
  
  library(viridis)

```

```{r message = FALSE, echo = FALSE, error = FALSE, warning = FALSE}
  
  # Using the preloaded data to make our plot
  
  boston_weather %>% 
    # Extracting the month from a column we have
  
    mutate(t_month = month(DATE, label = TRUE, abbr = FALSE)) %>%
    # Grouping by month
  
    group_by(t_month) %>%
    # Making sure January is at the top of the plot and filling by temperature
  
    ggplot(aes(x = TMAX, y = fct_rev(t_month), fill = ..x..)) +
    # Making a density plot
  
    geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
    # Using a color scheme that is useful to portray temperature  
  
    scale_fill_viridis(name = "Temp. [F]", option = "A") +
    # Adding appropriate title, subtitle and source citation to the plot
  
    labs(title = 'Maximum Daily Temperature in Boston: 1936 -- 2019',
         subtitle = 'Recorded at Boston Logan Airport',
         caption = 'Source: NOAA') +
    xlab("Temperature") +
    ylab(NULL)
```
